---
name: Net-OBEX-FTP
version: 0.002
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: implemenation of OBEX File Transfer Profile
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  Net::OBEX: 0.002
  XML::OBEXFTP::FolderListing: 0.002
configure_requires:
  Module::Build: 0.34
provides:
  Net::OBEX::FTP:
    file: lib/Net/OBEX/FTP.pm
    version: 0.002
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
